name: Source container build

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/source-build.yaml
    - source-container-build/**

  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/source-build.yaml
    - source-container-build/**

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run checks
      run: |
        python3 -m pip install tox
        cd ./source-container-build/app/
        tox
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./source-container-build/Dockerfile
